from __future__ import annotations

import pandas as pd

START_DATE = pd.Timestamp("2019-01-01")
MAX_TRAINING_DATE = pd.Timestamp("2024-12-31")
VARIANCE_THRESHOLD = 750.0
MIN_MONTHS_PER_COMBINATION = 12
FORECAST_PERIODS_MONTHS = 24
TARGETS = ("resistenti", "intermedi", "sensibili")

ANTIBIOTIC_CLASS_CODES = {
    "GLICOPEPTIDI": ["VAN", "TPL"],
    "LIPOPEPTIDI": ["DAP"],
    "MACROLIDI": ["ERY", "AZM"],
    "NITROFURANI": ["NIT"],
    "OSSAZOLIDINONI": ["LZD"],
    "CEFALOSPORINE II": ["FOX"],
    "CEFALOSPORINE V": ["CPT"],
    "PENICILLINE": ["AMP"],
    "CEFALOSPORINE III + INIBITORE": ["CAZ", "CZA"],
    "CEFALOSPORINE IV": ["FEP"],
    "CEFALOSPORINE V + INIBITORE": ["CZT"],
    "POLIMIXINE": ["COL"],
    "LICOPEPTIDI": ["DAP"],
    "RIFAMPICINE": ["RIF"],
    "TETRACILLINE": ["TGC"],
    "AMMINOGLICOSIDI": ["AMK", "GEN"],
    "FOSFOMICINA": ["FOS"],
    "PENNICILLINE + INIBIITORE": ["AMC"],
}

INTRINSIC_RESISTANCE_EXCLUSIONS = {
    "KLEPNE": ["GLICOPEPTIDI", "LIPOPEPTIDI", "MACROLIDI", "NITROFURANI", "OSSAZOLIDINONI"],
    "ACISPP": ["CEFALOSPORINE II", "CEFALOSPORINE V", "GLICOPEPTIDI", "LIPOPEPTIDI", "MACROLIDI", "OSSAZOLIDINONI", "PENICILLINE"],
    "ENTFCM": ["CEFALOSPORINE II", "CEFALOSPORINE III + INIBITORE", "CEFALOSPORINE IV", "CEFALOSPORINE V", "CEFALOSPORINE V + INIBITORE", "POLIMIXINE"],
    "ESCCOL": ["GLICOPEPTIDI", "LIPOPEPTIDI", "MACROLIDI", "NITROFURANI", "OSSAZOLIDINONI"],
    "ENTFAE": ["CEFALOSPORINE II", "CEFALOSPORINE III + INIBITORE", "CEFALOSPORINE IV", "CEFALOSPORINE V + INIBITORE", "POLIMIXINE"],
    "PSEAER": ["CEFALOSPORINE II", "CEFALOSPORINE V", "LICOPEPTIDI", "LIPOPEPTIDI", "MACROLIDI", "OSSAZOLIDINONI", "RIFAMPICINE", "TETRACILLINE"],
    "STAAUR": ["CEFALOSPORINE V + INIBITORE", "NITROFURANI", "POLIMIXINE"],
    "STRPNE": ["AMMINOGLICOSIDI", "CEFALOSPORINE II", "CEFALOSPORINE III + INIBITORE", "CEFALOSPORINE IV", "CEFALOSPORINE V", "CEFALOSPORINE V + INIBITORE", "FOSFOMICINA", "OSSAZOLIDINONI", "PENNICILLINE + INIBIITORE", "RIFAMPICINE"],
}
